services:
  - type: web
    name: ipt-final-2025-frontend
    env: static
    buildCommand: npm install -g react-scripts && npm install && CI=false npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://finalintproggroupf.onrender.com/api
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 